Add show_error_codes option to mypy config (#5032)
This causes mypy to show error codes in its output, which can be used to ignore specific type errors rather than blanket ignores. For example, given an error like:
```
cirq-core/cirq/_compat.py:37: error: Name 'cached_property' already defined (possibly by an import)  [no-redef]
```
we can then do:
```python
from backports.cached_property import cached_property  # type: ignore[no-redef]
```
Which ignores just that specific type error and also helps document what the error is.